[PR3] DEV-3 Measurement
HyperloopUPV-H8/Backend-H8 pull request #10
Opened 2022-10-23 19:14 UTC by smorsua

Falta por implementar la conversión de unidades

2022-10-24 17:58 UTC, jmaralo requested changes
Lo que he visto es que aun no esta terminado Value.go, el resto esta bien

2022-10-24 17:58 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/ranges.go
> +	return Ranges{safe: safeRange, warning: warningRange}
en vez de hacer primero una variable y luego asignárselo a los valores del struct usa directamente la funcion dentro del struct
```suggestion
	return Ranges{
	    safe: getRangesFromString(strings.ReplaceAll(safeRangeStr, " ", "")),
	    warning: getRangesFromString(strings.ReplaceAll(warningRangeStr, " ", ""))
	}
```

2022-10-24 17:58 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/value/bool.go
> +
evita subir código comentado

2022-10-24 17:58 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/value/number/float.go
> +	displayUnits Unit
porque aqui tambien defines `podUnits` y `displayUnits` si ya tienes el struct `Units`?

2022-10-24 17:58 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/value/number/units.go
> +package number
este archivo se puede separar en dos. En este dejas `Unit` y `Units` y en el otro metes `Operation`

2022-10-24 17:58 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/value/value.go
> +			return new(String)
Esta logica siempre ejecuta esta opcion porque `isEnum` siempre devuelve true

2022-10-24 17:58 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/value/value.go
> +		return new(Bool)
No veo donde defines new.
La logica de este archivo esta sin terminar.

2022-10-24 17:59 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/value/bool.go
> +
vale, aun no estaba cambiado mientras escribía la review

2022-10-24 17:59 UTC, smorsua commented on src/DataTransfer/podDataCreator/domain/measurement/ranges.go
> +	return Ranges{safe: safeRange, warning: warningRange}
Prefiero que este separado para que no sea muy largo

2022-10-24 18:00 UTC, smorsua commented on src/DataTransfer/podDataCreator/domain/measurement/value/number/float.go
> +	displayUnits Unit
Tengo que borrar Units

2022-10-24 18:02 UTC, smorsua commented on src/DataTransfer/podDataCreator/domain/measurement/value/value.go
> +			return new(String)
Cierto, esa función la tengo, pero le hace falta a PacketParser, hasta que no veamos donde colocarla, la dejo ahí

2022-10-26 23:08 UTC, jmaralo requested changes
cositas para facilitarte el error handling y algun tema de convenciones. Poca cosa pero que hay que mirar

2022-10-26 23:08 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/ranges.go
> +		fmt.Printf("Error parsing ranges regExp: %v\n", err)
Este error te lo ahorras con lo que te he dicho, pero para el futuro. Para dar formato a los errores en go se hace por convencion todo en minuscula y, como tu has hecho, con la forma "*causa*: *error*" (una [discusion](https://github.com/golang/go/issues/29934) del repo de go que habla sobre errores y se ve el formato del error en todas partes)

2022-10-26 23:08 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/ranges.go
> +		fmt.Printf("Error parsing int: %v\n", err)
lo de antes de las mayusculas en los mensajes de error. Se que no necesitamos seguir al pie de la letra las convenciones de go, pero si podemos mejor.

2022-10-26 23:08 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/value/number/Number.go
> +	value        float32
el tipo mas grande es `float64`

2022-10-26 23:08 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/value/number/operations.go
> +	opExp, err := regexp.Compile(`([+\-\/*]{1})(\d+)`)
`regex.MustCompile`

2022-10-26 23:08 UTC, jmaralo commented on src/DataTransfer/podDataCreator/domain/measurement/value/number/units.go
> +	unitExp, err := regexp.Compile(`^([a-zA-Z]+)#((?:[+\-\/*]{1}\d+)+)#$`)
`regex.MustCompile`

2022-10-27 08:46 UTC, jmaralo approved these changes
lgtm

2022-10-27 10:04 UTC, lipezaballa commented on src/DataTransfer/podDataCreator/domain/measurement/value/number/units.go
> +func undoUnits(number float64, operations []Operation) float64 {
Porque es necesario revertir operaciones para devolver valores anteriores? para qué es este método?

2022-10-27 10:09 UTC, lipezaballa approved these changes

2022-10-27 14:55 UTC, closed without merging