[PR1] DEV-12: MVP-1 logger
HyperloopUPV-H8/Backend-H8 pull request #21
Opened 2022-10-31 17:29 UTC by lipezaballa

It creates a file that overwrites the previous run, from each package it prints the props we are interested in, as well as each measurement.

2022-10-31 17:33 UTC, smorsua requested changes
LGTM, I'll aprove it once you make the changes suggested

2022-10-31 17:33 UTC, smorsua commented on src/DataTransfer/application/data_transfer.go
> +		titlePacket := fmt.Sprintf(`Id: %v    Name: %v    Count: %v    CycleTime: %v`,
Mete lo de escribir en el file dentro de una función.

2022-10-31 17:33 UTC, smorsua commented on src/DataTransfer/application/data_transfer.go
> +
```suggestion
 defer logFile.Close()
```

2022-10-31 17:36 UTC, jmaralo submitted a review, later dismissed
looks great, we'll need to perform benchmarks to make sure everything is fast enough

2022-11-01 12:18 UTC, jmaralo submitted a review, later dismissed

2022-11-02 16:09 UTC, smorsua approved these changes
Buen trabajo

2022-11-02 16:15 UTC, smorsua approved these changes

2022-11-02 16:18 UTC, smorsua submitted a review, later dismissed

2022-11-02 16:22 UTC, smorsua approved these changes

2022-11-02 16:23 UTC, jmaralo approved these changes

2022-11-02 16:23 UTC, merged