[PR1] DEV-22:
HyperloopUPV-H8/Backend-H8 pull request #31
Opened 2022-11-05 11:59 UTC by lipezaballa

filter excel "BOARD" sheets, use relatives path to credentials, corrected .env and json location to src. Some prints to see parseTable error in Sheet 3 excel test

2022-11-05 12:59 UTC, jmaralo commented
I just added a commit to fix some bugs with the logic of excel reader.

What happend was that when it found a table that was on "the edge" (the bottom right corner) it tried to parse it iterating the elements of two axes until it found blank space, then it would update the table bound with those values. Because once we reach that corner there is no more data to be read the loop ended without finding empty cells because for the excel there were no more cells in the sheet and it would say that the table had 0 rows and 0 cols.

Also we need to change the logic because right now it only checks the first column and the first row to get the dimensions, but maybe some elements are missing or columns have different sizes and we end up with an smaller table than real one, missing necessary information but thinking that what we got is all that exists on that table.

2022-11-05 14:50 UTC, jmaralo commented
This last commit should fix all known bugs

2022-11-05 18:59 UTC, smorsua requested changes

2022-11-05 18:59 UTC, smorsua commented on src/Shared/excel_retriever/excelRetriever.go
> +	infra.FetchExcel(os.Getenv("SPREADSHEET_ID"), fileName, filePath, credentialsPath)
Make the SPREADSHEET_ID a parameter like the credentialsPath

2022-11-05 18:59 UTC, smorsua commented on src/Shared/excel_retriever/infra/downloadExcel.go
> +	filePath := credentialsPath + os.Getenv("SECRET_FILE_PATH")
Receive SECRET_FILE_PATH as parameter

2022-11-05 18:59 UTC, smorsua commented on src/Shared/excel_retriever/infra/readExcel.go
> +	fmt.Print("boards filtered: ")
Remove prints

2022-11-05 18:59 UTC, smorsua commented on src/Shared/excel_retriever/infra/readExcel.go
> +			log.Fatalf("get rows: %s\n", err)
Make the error say "error gettings columns"

2022-11-05 18:59 UTC, smorsua commented on src/Shared/excel_retriever/infra/readExcel.go
> +		cols, err := file.GetCols(name)
Make a function called getCols and return only the columns. The error handling of file.GetCols would be done inside this new function

2022-11-05 18:59 UTC, smorsua commented on src/Shared/excel_retriever/infra/readExcel.go
> +func findTableEnd(cols [][]string, firstCol int, firstRow int) (bound [2]int) {
Split into two functions: findTableWidth y findTableHeight

2022-11-05 18:59 UTC, smorsua commented on src/Shared/excel_retriever/infra/readExcel.go
> +	fmt.Print("Parse Table, bound[3]-bound[1]-2: ")
remove prints

2022-11-06 10:36 UTC, smorsua submitted a review, later dismissed

2022-11-06 10:37 UTC, jmaralo requested changes
just a few minor things before merging

2022-11-06 10:37 UTC, jmaralo commented on src/Shared/excel_retriever/excelRetriever.go
> +	//os.Getenv("SPREADSHEET_ID")
commented code

2022-11-06 10:37 UTC, jmaralo commented on src/Shared/excel_retriever/infra/downloadExcel.go
> +	//filePath := credentialsPath + os.Getenv("SECRET_FILE_PATH")
commented code

2022-11-06 10:37 UTC, jmaralo commented on src/cmd/MVP-1/main.go
>  package main
we shouldn't be editing the MVP-1 main when we changes change the code, the MVP-1 was a previous varsion and all of this is for the next MVP

2022-11-06 10:45 UTC, jmaralo approved these changes

2022-11-06 10:47 UTC, smorsua approved these changes

2022-11-06 10:47 UTC, merged