Added podData adapters
HyperloopUPV-H8/Backend-H8 pull request #5
Opened 2022-10-20 14:31 UTC by smorsua

Estas clases coge los objetos que le devuelve el excelParser y los transforma en structs que serán usados para crear el podData más cómodamente

2022-10-20 15:31 UTC, smorsua commented
El paquete excel que uso no existe, eso nos lo dará Felipe. Si queréis que lo suba lo tengo en local (es un archivo con varios structs)

2022-10-20 16:20 UTC, jmaralo reviewed
Todo lo que he visto son cosas de como hacerlo para que el codigo este mas claro y menos redundante. Esta bien pero seguro que hay alguna manera de hacerlo en la que no repitamos tanto codigo

2022-10-20 16:20 UTC, jmaralo commented on src/DataTransfer/podDataStructure/infra/adapters/utils/idExpander.go
> +func isNumber(id string) bool {
esta funcion (y `stringToInt`, `getRange` y `rangeToString`) se podria meter en otro archivo (por ejemplo stringParser.go), porque no sirve para expandir ids, solo para comprobar si el string es un numero (en este caso)

2022-10-20 16:20 UTC, jmaralo commented on src/DataTransfer/podDataStructure/infra/adapters/boardAdapter.go
> +	descriptions := make(map[string]DescriptionAdapter)
esta funcion y `addMeasurements` son practicamente iguales excepto que cada una actualiza una parte distinta de `BoardAdapter`, se podrian combinar en una sola  `getRows` usando generics que devuelva un valor y luego desde el constructor asignar el valor de cada atributo de `BoardAdapter`.

Tambien pienso que en vez de mutar el objeto podrian devolver una lista de adaptadores y desde el constructor hacer `boardAdapter.descriptions = getDescriptions(table)`

2022-10-22 18:44 UTC, Piper050 requested changes
Perdon por usar la cuenta personal 😞

2022-10-22 18:44 UTC, Piper050 commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/idExpander/idExpander.go
> +func getIdParts(id string) (string, string, string) {
no es algo necesario, pero queda mas expresivo si escribes el tipo de retorno como `(prefix, begin, end string)`

2022-10-22 18:44 UTC, Piper050 commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/idExpander/idExpander.go
> +		str := strconv.Itoa(int(num))
el `int(num)` es redundate porque ya le pasas una lista de int

2022-10-22 18:44 UTC, Piper050 commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/PacketDTO.go
> +func (p *PacketDTO) toPacket() podDataCreator.Packet {
de nuevo variable de una letra `p` y puntero que no deberia ser puntero

2022-10-22 18:44 UTC, Piper050 commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/PacketDTO.go
> +		Timestamp:    time.Now(), //FIXME: que valor le pongo a esto?
(no es un RFC) para que se va a usar esta timestamp?

2022-10-22 18:44 UTC, Piper050 commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func getMeasurementDTOs(table excelRetreiver.Table) map[string]MeasurementDTO {
cuando devuelvas o uses un valor internamente ponle un alias a los tipos que representan algo concreto, en este caso puedes cambiar `string` por algo como `Name` o algo asi mas representativo de su valor, es mucho mas descriptivo `map[Name]MeasurementDTO` que `map[string]MeasurementDTO`

2022-10-22 18:44 UTC, Piper050 commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +			column = append(column, table.Rows[j][i])
evita usar append, que aunque no va a ser nunca nuestro cuello de botella la velocidad de append comparado con hacer un set (cuando tienes una slice de la que conoces su longitud) se nota, y mas porque en tu codigo usas bastantes fors

2022-10-22 18:50 UTC, jmaralo requested changes
Muchas cosas de las que he visto solo las he puesto en el primer sitio en las que las he encontrado para evitar poner muchos comentarios iguales.

Lo que he visto es que usas mucho `append` en sitios donde conoces de antemano la longitud de la slice. Utiliza los segundos argumentos de `make()` para evitar alocar multiples veces objetos en memoria y ahorrarte tiempo. Puedes hacer tanto con append (`arr := make([]type, 0, length); arr = append(arr, type)`)como haciendo set (`arr := make([]type, length); arr[n] = type`) y es el [doble de rapido](https://daryl-ng.medium.com/why-you-need-to-avoid-using-append-in-go-8c8502b5d0da)

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func NewBoardDTO(tables map[string]excelRetreiver.Table) BoardDTO {
excelRetreiver define ya Document que tiene dentro Sheets que es de este tipo, porque no usamos Document y accedemos a Sheets en vez de pedirle ya map[string]Sheet?

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +		structures:   structures,
Esta bien, pero en vez de primero crear una variable y luego crear el objeto con las variables de antes, inicializa directamente el valor de los atributos del struct con la funcion correspondiente

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func (b *BoardDTO) GetPackets() map[uint16]*podDataCreator.Packet {
nombre de una letra `b` y puntero que realmente no es necesario, no estas mutando los valores

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func getMeasurementDTOs(table excelRetreiver.Table) map[string]MeasurementDTO {
cuando devuelvas o uses un valor internamente ponle un alias a los tipos que representan algo concreto, en este caso puedes cambiar `string` por algo como `Name` o algo `asi` mas representativo de su valor, es mucho mas descriptivo `map[Name]MeasurementDTO` que `map[string]MeasurementDTO`

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +	measurements := make(map[string]MeasurementDTO)
sabemos de antemano la cantidad de elementos que va a tener measurements, pasale eso como segundo valor y te ahorras que se este alocando memoria varias veces

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +			column = append(column, table.Rows[j][i])
evita usar append, que aunque no va a ser nunca nuestro cuello de botella la velocidad de append comparado con hacer un set (cuando tienes una slice de la que conoces su longitud) se nota, y mas porque en tu codigo usas bastantes fors

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +	}
Puedes separar esta logica en otra funcion

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/PacketDTO.go
> +func (p *PacketDTO) toPacket() podDataCreator.Packet {
de nuevo variable de una letra `p` y puntero que no deberia ser puntero

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/PacketDTO.go
> +		Timestamp:    time.Now(), //FIXME: que valor le pongo a esto?
(no es un RFC) para que se va a usar esta timestamp?

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/StructureDTO.go
> +func newStructure(column []string) StructureDTO {
por continuar con el esquema de nombres deberia llamarse `newStructureDTO`

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/idExpander/idExpander.go
> +func getIdParts(id string) (string, string, string) {
no es algo necesario, pero queda mas expresivo si escribes el tipo de retorno como `(prefix, begin, end string)`

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/idExpander/idExpander.go
> +		str := strconv.Itoa(int(num))
el `int(num)` es redundate porque ya le pasas una lista de int

2022-10-22 18:50 UTC, jmaralo commented on src/DataTransfer/podDataStructure/infra/adapters/boardAdapter.go
> +package adapters
Entiendo que estos archivos son los viejos no?
Si son los viejos acuerdate de borrarlos, y tambien el .gitignore

2022-10-22 19:11 UTC, smorsua commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func (b *BoardDTO) GetPackets() map[uint16]*podDataCreator.Packet {
El nombre de una letra me parece adecuado, los paquetes de Go lo escriben asi, y la función la recibe un puntero

2022-10-22 19:12 UTC, smorsua commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func NewBoardDTO(tables map[string]excelRetreiver.Table) BoardDTO {
No entiendo

2022-10-22 19:14 UTC, smorsua commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/PacketDTO.go
> +		Timestamp:    time.Now(), //FIXME: que valor le pongo a esto?
Para calcular el cycle time

2022-10-22 19:58 UTC, smorsua commented on src/go.mod
> +
lo dejo por si acaso, luego al mergear ya veremos

2022-10-22 20:01 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/PacketDTO.go
> +		Timestamp:    time.Now(), //FIXME: que valor le pongo a esto?
pues no se que valor le puedes poner, de momento supongo que time.Now() esta bien, ya se cambiara

2022-10-22 20:06 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func NewBoardDTO(tables map[string]excelRetreiver.Table) BoardDTO {
Vale nada, me he liado leyendo el PR de DEV-2, esta bien

2022-10-22 20:15 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func (b *BoardDTO) GetPackets() map[uint16]*podDataCreator.Packet {
ya, pero creo que queda mejor algo mas largo que da mas información de lo que es, por ejemplo en este caso yo pondria `board` en vez de `b`. Que no esta mal lo que has escrito, son todo funciones muy cortas que en un momento puedes buscar el nombre, pero por no tener nombres de una letra que al final no te dan nada de informacion.

(a mi tambien me paso en mi PR que puse nombres de una letra a los objetos, pero al cambiarlos se entiende mejor el codigo)

2022-10-22 20:21 UTC, jmaralo reviewed
No es por ser pesado, pero te marco algun append que te has dejado y del que sabes la longitud de la lista

2022-10-22 20:21 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/idExpander/idExpander.go
> +		finalIds = append(finalIds, prefix+sufix)
aqui tambien usas append y sabes la longitud

2022-10-22 20:21 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/idExpander/idExpander.go
> +		numRange = append(numRange, n)
y aqui

2022-10-22 20:21 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/idExpander/idExpander.go
> +		rangeInString = append(rangeInString, str)
append

2022-10-22 20:21 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/MeasurementDTO.go
> +		mArr = append(mArr, measurement)
otro append

2022-10-22 20:21 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/PacketDTO.go
> +		packetDTOs = append(packetDTOs, newPacket)
otro append

2022-10-23 10:11 UTC, smorsua commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func (b *BoardDTO) GetPackets() map[uint16]*podDataCreator.Packet {
Se entiende mejor pero es demasiado redundante, prefiero obligarme a escribir funciones tan sencillas que no se te olvida lo que es b porque hay poco código

2022-10-23 10:12 UTC, jmaralo commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +func (b *BoardDTO) GetPackets() map[uint16]*podDataCreator.Packet {
ok

2022-10-23 10:14 UTC, jmaralo approved these changes
pinta bien

2022-10-23 10:47 UTC, Losina24 approved these changes

2022-10-23 10:47 UTC, Losina24 commented on src/DataTransfer/podDataCreator/podDataCreator.go
> +func New() domain.PodData {
cambia New por Invoke y estaria gucci (porque New es el constructor, lo que estarías creando es un PodDataCreator, si lo que quieres es crear un PodData deberias llamar a otro metodo -> invoke())

2022-10-23 10:49 UTC, smorsua commented on src/DataTransfer/podDataCreator/podDataCreator.go
> +func New() domain.PodData {
Lo añado en el siguiente PR2

2022-10-23 20:48 UTC, lipezaballa submitted a review, later dismissed
he comentado dos tonterías, pero lo veo genial

2022-10-23 20:48 UTC, lipezaballa commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +		for j := 0; j < len(table.Rows); j++ {
Es una tontería, pero igual es mas legible si se hace método para getColumn

2022-10-24 16:02 UTC, smorsua commented on src/DataTransfer/podDataCreator/infra/excelAdapter/dto/BoardDTO.go
> +
Recorren tablas diferentes

2022-10-24 16:21 UTC, jmaralo approved these changes
excepto por esa cosilla que te he comentado todo bien

2022-10-24 16:21 UTC, jmaralo commented on src/DataTransfer/DataTansfer.go
> +func (dataTransfer *DataTransfer) New() {
Porque haces esto así y no devolviendo un nuevo objeto cuando llamas new?

2022-10-25 13:47 UTC, lipezaballa approved these changes

2022-10-27 08:47 UTC, jmaralo submitted a review, later dismissed

2022-10-27 16:41 UTC, jmaralo approved these changes

2022-10-27 16:41 UTC, merged