[PR1] DEV-1 Add TransportController
HyperloopUPV-H8/Backend-H8 pull request #6
Opened 2022-10-20 22:53 UTC by jmaralo

Abro nuevo PR porque ha cambiado bastante desde la ultima vez y practicamente todo se queda outdated.
(Perdon por adelantado por un PR tan grande)

En este PR añado el TransportController y he separadola logica en varios archivos.

Tambien tras hablar con FW nos hemos dado cuenta de que el enfoque que teniamos antes de conectarnos nosotros al pod es erroneo. El backend actua como servidor y el pod como cliente y por tanto no tenemos que estar comprobando las placas todo el rato, lo que "simplifica" la logica. Por ello la interfaz del TransportController ahora implementa dos metodos Receive, uno para leer del sniffer y otro para leer del server TCP

Si veis `snifferFilters.go` hay una interfaz llamada `Filterer`, no es un typo, mirad esta [diapositiva](https://go.dev/talks/2014/names.slide#13) de una charla de go donde hablan de como poner nombre a las cosas.
(hay un comentario que lo explica por si acaso)

2022-10-20 22:54 UTC, jmaralo commented
en muchos commits se me ha olvidad poner al principio que son para DEV-1 :(
se les puede cambiar de alguna forma?

2022-10-21 10:28 UTC, smorsua requested changes

2022-10-21 10:28 UTC, smorsua commented on src/Shared/PacketAdapter/infra/server.go
> +	connections map[IP]*net.TCPConn
Usa sync.Map y te ahorras tanto el mutex y como tener que hacer lock

2022-10-21 10:28 UTC, smorsua commented on src/Shared/PacketAdapter/infra/server.go
> +func (server *Server) filterValidAddr(addr IP) bool {
Esta lógica se la metes al sniffer, y este solo devuelve los paquetes que pasan el filtro.

2022-10-21 10:32 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/server.go
> +func (server *Server) filterValidAddr(addr IP) bool {
esa es logica del server TCP, filtra las conexiones que se intentan conectar al servidor para que solo se conecten las ips que esperamos, para que no se conecte una ip random y envie paquetes maliciosos

2022-10-21 10:38 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/server.go
> +	connections map[IP]*net.TCPConn
estaba dudando de si usarlo o no por una parte de la [documentacion](https://pkg.go.dev/sync#Map) que dice:
> The Map type is specialized. Most code should use a plain Go map instead, with separate locking or coordination, for better type safety and to make it easier to maintain other invariants along with the map content.
y luego dice los dos casos para los que esta enfocado.

Pensandolo ahora si que cumpliríamos el primer caso en nuestro codigo (escribimos solo cuando se conecta una conexion) asi que lo cambiare a sync.Map.

2022-10-21 10:39 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/server.go
> +func (server *Server) listenConnections() {
ok

2022-10-21 10:40 UTC, jmaralo commented
Aunque no son muchos cambios los incluyo en el siguiente PR en el que estoy trabajando y los meto junto con el testing. Hare un draft PR cuando tenga los cambios en la rama

2022-10-21 10:53 UTC, smorsua commented on src/Shared/PacketAdapter/infra/server.go
> +	connections map[IP]*net.TCPConn
Al final hemos llegado a la conclusión de usar un map normal con un mutex pero hacer métodos separados para leer y escribir, en los cuales llamamos a mutex.lock

2022-10-21 21:57 UTC, Losina24 requested changes
En general bastante bien, se nota una mejor calidad del codigo que en el anterior PR. Si pulimos estos detallines nos queda una buena base sobre la que ir desarrollando

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/server.go
> +		connections: make(map[IP]*net.TCPConn, len(remoteAddrs)),
si vas a meterlo en un mapa puedes sacarlo a un objeto para darle mas semantica. Las clases son gratis

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/server.go
> +			continue
es recomendable no usar ni brakes ni continue

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/server.go
> +			continue
yo buscaria otra alternativa, utilizando excepciones o sacandolo a un metodo y haciendo return

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/server.go
> +			continue
lo mismo

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/server.go
> +	return nil
este metodo habria que refactorizarlo entero,

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/server.go
> +func (server *Server) filterValidAddr(addr IP) bool {
mejor llamarlo: isValidAddr, porque devuelve un boolean, no un Addr

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/sniffer.go
> +	if live {
puedes sacar este if else a un metodo que tenga esta logica y aqui llamar ese metodo simplemente

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/sniffer.go
> +			continue
triple kill de continues

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/snifferFilters.go
> +		}
esto me salta las alarmas, que se supone que hace este metodo (si no se entiende a simple vista es que deberiamos refactorizar, pero no es ese el punto, esta logica me parece extraña)

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/transportController.go
> +
da gusto ver una clase asi

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/aliases.go
> +	return
que return mas misterioso, es por algo de go?

2022-10-21 21:57 UTC, Losina24 commented on src/Shared/PacketAdapter/infra/server.go
> +	packetMaxLength int = 1024
PACKET_MAX_LENGTH

2022-10-22 09:40 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/snifferFilters.go
> +		}
comprueba que un paquete se ha enviado entre dos ips que estan en una lista

2022-10-22 09:42 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/aliases.go
> +	return
es porque le he puesto nombre (`ips`) a la variable de retorno y por eso al hacer return go sabe que lo que estoy devolviendo es la variable con ese nombre. Pero lo cambiare porque quizas para alguien que nunca ha tocado go esto puede ser nuevo y asi queda mas explicito lo que devuelve

2022-10-22 09:46 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/server.go
> +	packetMaxLength int = 1024
en go los nombres de las constantes van en camel-case (usando la primera letra mayuscula o minuscula para la privacidad) y en raras veces todo en mayusculas (solo si son adoptadas de otros sitios).
Al menos es asi como se escribe en la libreria estandard de go.

2022-10-22 09:47 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/snifferFilters.go
> +		}
asi ahora no veo ninguna manera de hacerlo mas claro, pero le echare un ojo

2022-10-22 09:48 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/server.go
> +func (server *Server) filterValidAddr(addr IP) bool {
bien, lo actualizo en el siguiente PR

2022-10-22 09:49 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/server.go
> +	return nil
si, estuve hablando con Sergio y aun encima ahora estoy teniendo problemas para hacerlo funcionar, en el siguiente PR habrá una mejora

2022-10-22 09:50 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/server.go
> +			continue
no entiendo porque no es recomendable no usar brakes ni continues? es porque hace el código mas difícil de leer?

2022-10-22 09:51 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/server.go
> +		connections: make(map[IP]*net.TCPConn, len(remoteAddrs)),
si, hare eso para simplificar lo del mutex, que me esta dando muchos quebraderos de cabeza tal y como esta

2022-10-22 17:09 UTC, jmaralo commented
Cuando podais mirad la segunda PR, en la que deberian estar todos los cambios propuestos. Si los veis bien mergeamos ya esta

2022-10-23 09:59 UTC, smorsua submitted a review, later dismissed
Lo apruebo teniendo en cuenta los cambios que has hecho en el PR2

2022-10-23 17:44 UTC, lipezaballa approved these changes
No he visto nada que me llamase la atención de forma negativa, es cierto que tampoco tengo mucha experiencia en transport controllers

2022-10-27 15:27 UTC, smorsua approved these changes

2022-10-27 16:39 UTC, merged