[PR1] DEV-2: Defining structs of Excel Parser and most of the excel reading
HyperloopUPV-H8/Backend-H8 pull request #7
Opened 2022-10-21 09:48 UTC by lipezaballa

excelParser.go contiene las structs que se crean una vez se termine de parsear el excel.
readExcel.go contiene métodos para leer un excel dado su nombre, a partir de él obtener sus hojas (getSheets), obtener las tablas de la hoja (aquí falta funcionalidad por implementar, tengo que obtener la parte de la hoja que interesa a cada tabla), y dada una tabla almacenar sus rows y los cells de cada row.

Me falta implementar el contenido de la tabla, posibilidad de hacer una copia de la hoja rectangular (inicialmente no es así y necesitamos que estén así las tablas) y descargar el excel de Drive.
Hay varios comentarios con cosas que faltan y posibles mejoras

2022-10-21 11:12 UTC, smorsua requested changes

2022-10-21 13:24 UTC, jmaralo reviewed
pinta bien, sobre todo cambia la ubicacion de go.mod de sitio para que no haya conflicto

2022-10-21 20:21 UTC, Losina24 requested changes

2022-10-21 20:21 UTC, Losina24 commented on src/DataTransfer/infra/excel/readExcel.go
> +			break
break == satanás
mucho mejor:
```go
// El método es más corto y se entiende mucho más rapido porque tiene menos indentaciones y no tengo que estar saltando entre lineas en caso de que la condicion no se cumpla
func getMaxRowLength(propertiesRow []string, initColumn int) int {
    maxLength := 0
    for i, cell := range propertiesRow {
        if isRightColumnAndNotEmptyCell(cell, init, i) {
            maxLength++
    }
    return maxLength
}

// Saco este método para darle más semántica y ver que esta haciendo de una pasada
func isRightColumnAndNotEmptyCell(cell, init, index) bool { 
    return initColumn >= i && cell != ""
}
```

2022-10-21 20:21 UTC, Losina24 commented on src/DataTransfer/infra/excel/readExcel.go
> +	for i := 0; i < len(sheetContent); i++ {
bucles dentro de bucles es sinonimo de que se pueden sacar cosas a otros metodos

2022-10-21 20:27 UTC, Losina24 commented on src/DataTransfer/infra/excel/readExcel.go
> +	//check that it is rectangular
es un "code smell" de manual, te dejo este post por si quieres saber más sobre el tema: https://refactoring.guru/es/refactoring/smells

2022-10-21 21:59 UTC, Losina24 requested changes
bastante guay, vamos a pulir estos detalles

2022-10-23 16:06 UTC, lipezaballa commented on src/DataTransfer/infra/excel/readExcel.go
> +
No te entiendo

2022-10-26 21:28 UTC, smorsua requested changes

2022-10-26 21:28 UTC, smorsua commented on src/DataTransfer/infra/excel/readExcel.go
> +		fmt.Println(name)
quitar print

2022-10-26 21:28 UTC, smorsua commented on src/DataTransfer/infra/excel/readExcel.go
> +	fmt.Println("finalColumn: ", finalColumn, " finalIndex: ", finalIndex, " emptySpacesAtEnd: ", emptySpacesAtEnd)
quitar print

2022-10-26 21:28 UTC, smorsua commented on src/DataTransfer/infra/excel/readExcel.go
> +		fmt.Println(len(row))
print

2022-10-26 21:28 UTC, smorsua commented on src/DataTransfer/infra/excel/readExcel.go
> +func getRowsOfTable(rectangularTable [][]string) []Row {
Esta función no hace nada porque el input es igual al output

2022-10-26 21:28 UTC, smorsua commented on src/DataTransfer/infra/excel/readExcel_test.go
> +	printSheetsName(mapa)
quitar print

2022-10-26 21:28 UTC, smorsua commented on src/DataTransfer/infra/excel/readExcel_test.go
> +	fmt.Println("Objeto creado: ", document)
Quitar print

2022-10-26 21:28 UTC, smorsua commented on src/DataTransfer/infra/excel/readExcel_test.go
> +func TestReadExcel(t *testing.T) {
Cual es el objetivo de este test?

2022-10-26 22:49 UTC, jmaralo requested changes
En general bien. A la lógica en si del programa no le he visto ningún fallo, pero hay cosas por ahí que hay que pulir antes de mergear para tener un buen codigo del que seguir construyendo en el futuro

2022-10-26 22:49 UTC, jmaralo commented on src/DataTransfer/infra/excel/downloadExcel.go
> +		log.Fatal(err, " client")
lo normal para el formato de error es poner "*causa*: *error*" y por costumbre, como este es un mensaje que termina el programa añade una linea al final con `Fatalln`
```suggestion
		log.Fatalln("client:", err)
```

2022-10-26 22:49 UTC, jmaralo commented on src/DataTransfer/infra/excel/downloadExcel.go
> +	mimeType := "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
esto mejor si es una constante fuera de la funcion

2022-10-26 22:49 UTC, jmaralo commented on src/DataTransfer/infra/excel/downloadExcel.go
> +		log.Fatal(err)
no esta de mas que como antes incluyas que el error lo ha producido la descarga

2022-10-26 22:49 UTC, jmaralo commented on src/DataTransfer/infra/excel/downloadExcel.go
> +func checkError(err error) {
esto que haces con `checkError` no tiene sentido. Lo usas para comprobar un error y si es un error parar por completo el programa (con `panic`), pero arriba en `download` lo usas dentro de un `if`, por lo que compruebas dos veces si el error no es `nil` y luego hay codigo muerto al que nunca vas a acceder. Te recomiendo que te deshagas de este metodo por completo y simplemente devuelvas el error en `download`

2022-10-26 22:49 UTC, jmaralo commented on src/DataTransfer/infra/excel/downloadExcel.go
> +	err = os.WriteFile(filename, b, 0644)
+1
```suggestion
                // 0644 gives the file owner permission to write and all other users permission to write
		err = os.WriteFile(filename, b, 0644) 
```

Por si alguien le interesa: en linux los permisos de un archivo se representan en binario (9 bits) donde cada bit es uno de los siguientes: rwxrwxrwx, donde r es read (permiso para leer), w es write (permiso para escribir), x es execute (permiso para ejecutar). Como son 3 trios el primero se corresponde con los permisos del propietario del archivo, el segundo los permisos del grupo del usuario y el tercero el resto de usuarios. Por lo tanto 0644 en binario es 110100100, que significa que cualquier usuario puede leer pero solo el owner puede editarlo.

2022-10-26 22:49 UTC, jmaralo commented on src/DataTransfer/infra/excel/downloadExcel_test.go
> +	downloadExcel(spreadsheetID, filename)
la librería de testing de go te permite crear [directorios temporales](https://pkg.go.dev/testing#T.TempDir) que se asegura de eliminar al final de la ejecucion

2022-10-26 22:49 UTC, jmaralo commented on src/DataTransfer/infra/excel/readExcel.go
> +	var initData [2]int = [2]int{axis[0] + 2, axis[1]}
porque utilizas la sintaxis de `:=` para declarar todas las variables y aqui usas `var *nombre* *tipo* =`?
Queda mas elegante:
```suggestion
	initData := [2]int{axis[0] + 2, axis[1]}
```

2022-10-26 22:49 UTC, jmaralo commented on src/DataTransfer/infra/excel/downloadExcel.go
> +		log.Fatal(err, "sheet")
lo mismo de antes para los errores

2022-10-26 22:49 UTC, jmaralo commented on src/go.mod
> +module github.com/HyperloopUPV-H8/Backend-H8
Mas que un RFC es una pregunta. En serio te pide tantas dependencias? prueba a ejecutar el comando `go mod tidy` para ver si se puede reducir el numero de dependencias, es porque se me hace raro que hagan falta tantas para una sola libreria

2022-10-26 22:49 UTC, jmaralo commented on src/DataTransfer/infra/excel/readExcel_test.go
> +func TestReadExcel(t *testing.T) {
La idea es usar los test para asegurarnos que el codigo funciona *de forma automatica*. Puedes usar un test que te de muchos prints y tal cuando estes programando para asegurarte de que lo que haces funciona, pero luego para el github actions necesitamos test que comprueben de manera automatica que funciona el codigo

2022-10-27 07:43 UTC, lipezaballa commented on src/go.mod
> +module github.com/HyperloopUPV-H8/Backend-H8
Ya hice el tidy y no redujo nada, a mí tb me extrañó bastante tantas dependencias. Quizá por la descarga del excel, acceso a credentials del proyecto, oauth, etc... Pero no sé si se puede reducir dependencias o realmente se necesitan esas y punto

2022-10-27 08:21 UTC, jmaralo commented on src/go.mod
> +module github.com/HyperloopUPV-H8/Backend-H8
ya, pues así se queda, era solo por curiosidad

2022-10-27 15:02 UTC, jmaralo reviewed
Son dos tontadas a cambiar antes de mergear.

2022-10-28 11:09 UTC, jmaralo approved these changes
lgtm

2022-10-28 11:12 UTC, jmaralo approved these changes
he resuelto el conflicto de mergeo que habia entre develop y features/DEV-2

2022-10-28 14:34 UTC, smorsua approved these changes
Buen trabajo

2022-10-28 14:48 UTC, merged