[PR2] [NO MERGE] DEV-1 Add unit tests and fix issues found
HyperloopUPV-H8/Backend-H8 pull request #8
Opened 2022-10-21 12:14 UTC by jmaralo

NO MERGEAR HASTA QUE ESTE APROBADO EL [PR ANTERIOR](https://github.com/HyperloopUPV-H8/Backend-H8/pull/6)

Añado test unitarios para el TransportController y soluciono algunos errores que he encontrado tanto haciendo los unit tests como de los RFC del anterior PR.

De momento es un draft para ver si se aprueban los cambios propuestos en el anterior PR (aunque añade algun test).

2022-10-21 12:43 UTC, smorsua commented on src/Shared/PacketAdapter/infra/transportController_test.go
> +func TestTransportController_ReceiveMessage(t *testing.T) {
No hace falta que pongas TrnasportController en el nombre de los tests

2022-10-21 13:25 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/transportController_test.go
> +func TestTransportController_ReceiveMessage(t *testing.T) {
si, se me ha colado porque use lo que te enseñe de vscode para hacer plantillas de tests y pone los nombres asi. Para el siguiente commit esta cambiado

2022-10-21 21:09 UTC, Losina24 commented
> NO MERGEAR HASTA QUE ESTE APROBADO EL [PR ANTERIOR](https://github.com/HyperloopUPV-H8/Backend-H8/pull/6)
> 
> Añado test unitarios para el TransportController y soluciono algunos errores que he encontrado tanto haciendo los unit tests como de los RFC del anterior PR.
> 
> De momento es un draft para ver si se aprueban los cambios propuestos en el anterior PR (aunque añade algun test).

No hace falta que pongas NO MERGE, se entiende poniendo PR2, el no merge se utiliza para cosas concretas

2022-10-22 17:42 UTC, jmaralo commented
La abro ya como PR porque aunque solo añade los unit test del TransportController ya son bastantes lineas para reviewear y asi vamos por partes

2022-10-23 09:56 UTC, smorsua requested changes
Lo veo bien, pero cambia las cosas que te he comentado antes

2022-10-23 09:56 UTC, smorsua commented on src/Shared/PacketAdapter/infra/transportController_test.go
> +func TestNewTransportController(t *testing.T) {
Ten una variable global que sea el server y usala en todos los test. Para que el server sea el mismo en todos los tests, usa la función T.Cleanup del paquete testing para hacer tc.Close(); tc = NewTransportController();

2022-10-23 09:56 UTC, smorsua commented on src/Shared/PacketAdapter/infra/transportController_test.go
> +	t.Run("block with no messages", func(t *testing.T) {
Crea de nuevo el TC para no depender del test anterior (usa lo de T.Cleanup)

2022-10-23 09:56 UTC, smorsua commented on src/Shared/PacketAdapter/infra/transportController_test.go
> +			conn := dialTCP("127.0.0.3:5999", fmt.Sprintf("127.0.0.1:%d", serverPort))
Porque lo haces en una goroutine aparte si estas esperando a que acabe con el done?

2022-10-23 09:56 UTC, smorsua commented on src/Shared/PacketAdapter/infra/server.go
> +	if err != nil {
Esta comprobación debe estar dentro de la funcion server.pipes.Send

2022-10-23 10:18 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/aliases.go
> +func payloadsToBytes(payloads []Payload) (bytes [][]byte) {
para devolveros a vosotros `[][]byte` y no `[]Payload` que es lo que  yo uso internamente, porque go convierte automaticamente de `Payload` a `[]byte` pero no de   `[]Payload` a `[][]byte`

2022-10-23 10:20 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/pipes.go
> +type SyncPipes struct {
porque esta pensado para usarlo en varias goroutines de manera sincronizada y sin carreras, pero si prefieres otro nombre lo puedo cambiar

2022-10-23 10:26 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/pipes.go
> +func (pipes SyncPipes) Close() {
en un principio si, porque aunque lo copias internamente net.Conn utiliza un puntero al file descriptor de la conexion, por lo que aunque yo copie la conexion ese puntero sigue apuntando al mismo lado. De todas lo probare para confirmarlo

2022-10-23 10:27 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/transportController_test.go
> +func TestNewTransportController(t *testing.T) {
entiendo lo que dices, pero que diferencia hay entre uno y otro?

2022-10-23 10:31 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/server.go
> +	if err != nil {
lo hice asi porque si llamo RemoveConnection dentro del Send de SyncPipes se bloquea permanentemente porque ya tiene el mutex lockeado Send y RemoveConnection bloquea hasta que pilla el lock. Pero ahora se me ha ocurrido una forma de hacerlo con goroutines que puede funcionar

2022-10-23 10:33 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/transportController_test.go
> +			conn := dialTCP("127.0.0.3:5999", fmt.Sprintf("127.0.0.1:%d", serverPort))
buena pregunta, ahora lo cambio

2022-10-23 10:34 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/transportController_test.go
> +	t.Run("block with no messages", func(t *testing.T) {
bien

2022-10-23 10:34 UTC, jmaralo commented on src/Shared/PacketAdapter/infra/transportController_test.go
> +func TestNewTransportController(t *testing.T) {
vale, que asi no depende el uno del otro, nada

2022-10-23 11:12 UTC, jmaralo commented
Meto los cambios que me has dicho en la siguiente PR, que si los meto en esta se hace muy grande. Subire el draft luego cuando termine el commit en el que estoy trabajando

2022-10-23 22:53 UTC, jmaralo commented
Acabo de subir cambios que estan en progreso tanto para poder seguir trabajando mañana desde el portatil como para que lo vayais viendo.

He decidido no hacer aun la PR3 porque no estaba contento con los test de TransportController, y como son los mas importantes porque como son los que deciden finalmente si funciona todo el conjunto o no voy a mejorarlos y luego ya hare los del resto para asegurarme que en efecto, todo funciona como se espera

2022-10-24 16:02 UTC, jmaralo commented
Ya debería estar, cuando podáis haced la review

2022-10-24 20:26 UTC, smorsua approved these changes
Buen trabajo

2022-10-27 09:53 UTC, lipezaballa approved these changes
Nada que añadir

2022-10-27 14:55 UTC, merged